services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./Backend:/app

  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:80"
